# Generated by Django 5.2.7 on 2025-11-13 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pendiente', 'Pendiente'), ('candidato', 'Candidato'), ('empleador', 'Empleador')], default='pendiente', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_profesional', models.TextField(blank=True, null=True)),
                ('habilidades', models.TextField(blank=True, help_text='Separadas por comas', null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDeEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada'), ('cerrada', 'Cerrada')], default='activa', max_length=10)),
                ('es_inclusion', models.BooleanField(default=False, help_text='Marcar si esta vacante se acoge a la Ley de Inclusión Laboral.', verbose_name='Oferta bajo Ley 21.015 (Inclusión)')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobswipe.categoriadeservicio')),
                ('perfil_empleador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_publicadas', to='jobswipe.perfil')),
            ],
            options={
                'verbose_name_plural': 'Ofertas de Empleo',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('User_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='jobswipe.ofertadeempleo')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
                'unique_together': {('oferta', 'User_candidato')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('User_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
                ('User_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='jobswipe.solicitud')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
