# Generated by Django 6.0 on 2025-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobswipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_pcd',
            field=models.BooleanField(default=False, verbose_name='Persona con Discapacidad'),
        ),
    ]
