# Generated by Django 6.0 on 2025-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobswipe', '0002_perfil_es_pcd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertadeempleo',
            name='moneda',
            field=models.CharField(blank=True, choices=[('CLP', 'Pesos Chilenos (CLP)'), ('USD', 'Dólares (USD)')], default='CLP', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ofertadeempleo',
            name='sueldo',
            field=models.PositiveIntegerField(blank=True, help_text='Opcional. Ej: 500000', null=True),
        ),
    ]
